#!/usr/bin/env csh -f 
#===============================================================================
# Automatically generated module settings for constance
# DO NOT EDIT THIS FILE DIRECTLY!  Please edit env_mach_specific.xml 
# in your CASEROOT. This file is overwritten every time modules are loaded!
#===============================================================================

source  /etc/profile.d/modules.csh
if( -x "./xmlquery") then
	set MPILIB = `./xmlquery MPILIB -value`
	set COMPILER = `./xmlquery COMPILER -value`
else
	set MPILIB mvapich2
	set COMPILER intel
endif
module purge 
module load perl/5.20.0
module load cmake/2.8.12
if ( $COMPILER == "intel" ) then
	module load intel/15.0.1
	module load netcdf/4.3.2
	module load mkl/15.0.1
endif
if ( $COMPILER == "pgi" ) then
	module load pgi/14.10
	module load netcdf/4.3.2
endif
if ( $MPILIB == "mvapich" ) then
	module load mvapich2/2.1
endif
if ( $MPILIB == "mvapich2" ) then
	module load mvapich2/2.1
endif
if ( $MPILIB == "intelmpi" ) then
	module load intelmpi/5.0.1.035
endif
if ( $MPILIB == "openmpi" ) then
	module load openmpi/1.8.3
endif
setenv OMP_STACKSIZE 64M
if ( $COMPILER == "intel" ) then
	setenv MKL_PATH $MLIB_LIB
	setenv NETCDF_HOME /share/apps/netcdf/4.3.2/intel/15.0.1
endif
if ( $COMPILER == "pgi" ) then
	setenv NETCDF_HOME /share/apps/netcdf/4.3.2/pgi/14.10
endif
