
#!/usr/bin/env sh -f 
#===============================================================================
# Automatically generated module settings for constance
# DO NOT EDIT THIS FILE DIRECTLY!  Please edit env_mach_specific.xml 
# in your CASEROOT. This file is overwritten every time modules are loaded!
#===============================================================================

    .  /etc/profile.d/modules.sh

if [ -x ./xmlquery  ]
then 
	MPILIB=`./xmlquery MPILIB -value`
	COMPILER=`./xmlquery COMPILER -value`
else
	MPILIB="mvapich2"
	COMPILER="intel"
fi
module purge  
module load perl/5.20.0 
module load cmake/2.8.12 
if [ "$COMPILER" = "intel" ]
then
	module load intel/15.0.1
	module load netcdf/4.3.2
	module load mkl/15.0.1
fi
if [ "$COMPILER" = "pgi" ]
then
	module load pgi/14.10
	module load netcdf/4.3.2
fi
if [ "$MPILIB" = "mvapich" ]
then
	module load mvapich2/2.1
fi
if [ "$MPILIB" = "mvapich2" ]
then
	module load mvapich2/2.1
fi
if [ "$MPILIB" = "intelmpi" ]
then
	module load intelmpi/5.0.1.035
fi
if [ "$MPILIB" = "openmpi" ]
then
	module load openmpi/1.8.3
fi
export OMP_STACKSIZE=64M
if [ "$COMPILER" = "intel" ]
then
	export MKL_PATH=$MLIB_LIB
	export NETCDF_HOME=/share/apps/netcdf/4.3.2/intel/15.0.1
fi
if [ "$COMPILER" = "pgi" ]
then
	export NETCDF_HOME=/share/apps/netcdf/4.3.2/pgi/14.10
fi
